name: edit_pnp
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2024.12.31
  - intel-openmp=2023.1.0
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.4
  - numpy-base=1.26.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.9.21
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - accelerate==0.20.3
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - attrs==24.3.0
      - bleach==6.2.0
      - blinker==1.9.0
      - blis==1.2.0
      - braceexpand==0.1.7
      - cachetools==5.5.1
      - catalogue==2.0.10
      - certifi==2024.12.14
      - cfgv==3.4.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpathlib==0.20.0
      - cmake==3.31.4
      - confection==0.1.5
      - contexttimer==0.3.3
      - contourpy==1.3.0
      - cycler==0.12.1
      - cymem==2.0.11
      - decorator==5.1.1
      - decord==0.6.0
      - diffusers==0.17.1
      - distlib==0.3.9
      - einops==0.8.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fairscale==0.4.4
      - filelock==3.17.0
      - fonttools==4.55.5
      - fsspec==2024.12.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - huggingface-hub==0.25.2
      - identify==2.6.6
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - iopath==0.1.10
      - ipython==8.18.1
      - jedi==0.19.2
      - jinja2==3.1.5
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kaggle==1.6.17
      - kiwisolver==1.4.7
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - lit==18.1.8
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - murmurhash==1.0.12
      - mypy-extensions==1.0.0
      - narwhals==1.23.0
      - networkx==3.2.1
      - nodeenv==1.9.1
      - numpy==2.0.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - omegaconf==2.3.0
      - opencv-python-headless==4.5.5.64
      - opendatasets==0.1.22
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - plotly==5.24.1
      - portalocker==3.1.1
      - pre-commit==4.1.0
      - preshed==3.0.9
      - prompt-toolkit==3.0.50
      - protobuf==5.29.3
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==19.0.0
      - pycocoevalcap==1.2
      - pycocotools==2.0.8
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydeck==0.9.1
      - pygments==2.19.1
      - pyparsing==3.2.1
      - pyre-extensions==0.0.29
      - python-dateutil==2.9.0.post0
      - python-magic==0.4.27
      - python-slugify==8.0.4
      - pytz==2024.2
      - pyyaml==6.0.2
      - referencing==0.36.1
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.22.3
      - safetensors==0.5.2
      - salesforce-lavis==1.0.0
      - scikit-image==0.24.0
      - scipy==1.13.1
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.1.0
      - smmap==5.0.2
      - spacy==3.8.3
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - stack-data==0.6.3
      - streamlit==1.41.1
      - sympy==1.13.3
      - tenacity==9.0.0
      - text-unidecode==1.3
      - thinc==8.3.4
      - tifffile==2024.8.30
      - timm==0.4.12
      - tokenizers==0.13.3
      - toml==0.10.2
      - torch==2.0.1
      - torchvision==0.15.2
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.30.2
      - triton==2.0.0
      - typer==0.15.1
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2025.1
      - urllib3==2.3.0
      - virtualenv==20.29.1
      - wasabi==1.1.3
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - weasel==0.4.1
      - webdataset==0.2.100
      - webencodings==0.5.1
      - wrapt==1.17.2
      - xformers==0.0.20
      - zipp==3.21.0
