name: edit_p2p
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - ca-certificates=2024.7.2
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - contourpy=1.0.5
  - cycler=0.11.0
  - dbus=1.13.18
  - expat=2.6.3
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - glib=2.63.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib_resources=6.4.0
  - intel-openmp=2021.4.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libffi=3.2.1
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.9.14
  - lz4-c=1.9.4
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - numpy-base=1.24.3
  - openjpeg=2.5.2
  - openssl=1.1.1w
  - packaging=24.1
  - pcre=8.45
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=3.10.0
  - pooch=1.7.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.8.0
  - python-dateutil=2.9.0post0
  - qt=5.9.7
  - readline=7.0
  - requests=2.32.3
  - scipy=1.10.1
  - setuptools=72.1.0
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.33.0
  - tk=8.6.14
  - tornado=6.4.1
  - unicodedata2=15.1.0
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==0.34.2
      - click==8.1.7
      - clip==0.2.0
      - diffusers==0.18.0
      - einops==0.8.0
      - face-alignment==1.4.1
      - filelock==3.16.0
      - ftfy==6.2.0
      - huggingface-hub==0.24.7
      - idna==3.10
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - joblib==1.4.2
      - lazy-loader==0.4
      - llvmlite==0.41.1
      - lpips==0.1.4
      - networkx==3.1
      - ninja==1.11.1.1
      - nltk==3.9.1
      - numba==0.58.1
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - opencv-python==4.10.0.84
      - psutil==6.0.0
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - regex==2024.9.11
      - safetensors==0.4.5
      - scikit-image==0.21.0
      - tifffile==2023.7.10
      - tokenizers==0.13.3
      - torch==1.13.1
      - torchmetrics==0.11.4
      - torchvision==0.14.1
      - tqdm==4.66.5
      - transformers==4.31.0
      - typing-extensions==4.12.2
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - zipp==3.20.2
